repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args:
        - --quiet
        - --line-length=120
        - --fix
        - --select
        - F # pyflakes
        - B # flake8-bugbear
        - I # isort
        # - NPY # numpy-specific rules
        # - --ignore
        # - F405
        # - --ignore
        # - F403 # ignore import *

  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.5.0
  #   hooks:
  #     - id: detect-secrets
  #       args: ['--baseline', '.secrets.baseline']
  #       exclude: |
  #         (?x)^(
  #             .*/tests/.*|
  #             .*/migrations/.*|
  #             .*/node_modules/.*
  #         )

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.56.0
  #   hooks:
  #     - id: eslint
  #       args: [--fix]
  #       additional_dependencies:
  #         - eslint@8.56.0
  #         - eslint-config-prettier@9.1.0
  #         - eslint-plugin-prettier@5.1.3
  #       files: \.[jt]sx?$  # .js, .ts, .jsx, .tsx
