# Generated by Django 4.2.24 on 2025-09-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_category_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
    ]
