# Generated by Django 4.2.24 on 2025-09-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='whatsapp_group_link',
        ),
    ]
