# Generated by Django 4.2.24 on 2025-10-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_whatsapp_group_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='utc_offset_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
