# Generated by Django 4.2.24 on 2025-10-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_profile_timezone_profile_utc_offset_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_shared',
            field=models.BooleanField(default=False, help_text='If True, any member of associated circles can edit this event'),
        ),
    ]
