# Generated by Django 4.2.24 on 2025-10-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_event_shared'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventparticipation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventparticipation',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventInvitation',
        ),
        migrations.DeleteModel(
            name='EventParticipation',
        ),
    ]
