# Generated by Django 4.2.24 on 2025-10-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventparticipation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(max_length=500),
        ),
    ]
