# Generated by Django 4.2.24 on 2025-10-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_address_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='is_invitation_circle',
            field=models.BooleanField(default=False, help_text='True if this is an invitation circle for an event'),
        ),
        migrations.AddField(
            model_name='circle',
            name='linked_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_circles', to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitation_token',
            field=models.CharField(blank=True, help_text='Token for invitation links', max_length=64, null=True, unique=True),
        ),
    ]
